name: continue delivery application to self-hosted k3s

on:
  push: 
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: 'v1.29.1'

      - name: Deploy to K3s
        env:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl --kubeconfig ${{ env.kubeconfig }} apply -f inf/