name: continue delivery application to self-hosted k3s

on:
  push: 
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: 'v1.29.1'

      - name: Create kubeconfig file
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > /tmp/kubeconfig

      - name: Deploy to K3s
        run: |
          kubectl --kubeconfig /tmp/kubeconfig apply -f inf/